image:
  file: .gitpod.DockerFile
tasks:
  - name: setup-python-311
    init: |
      # Install and set Python 3.11.8 via pyenv
      pyenv install -s 3.11.8
      pyenv global 3.11.8

      # Create a virtual environment
      python -m venv ~/.venvs/py311
      source ~/.venvs/py311/bin/activate

      # Install all required Python packages inside the venv
      pip install --upgrade pip
      pip install \
        html2text \
        jq \
        ipython-sql~=0.5 \
        sqlparse \
        SQLAlchemy \
        psycopg2-binary \
        pickleshare \
        pgspecial \
        pandas \
        six \
        ipykernel

      # Register this venv with Jupyter
      python -m ipykernel install --user --name=python311 --display-name "Python 3.11 (YB-friendly)"
    command: |
      echo "✅ Python 3.11 (YB-friendly) with Jupyter ipython kernel ready"
  - name: htop
    command: |
      htop
  - name: ybu-lab
    init: |
      (
        set -e
        chmod 777 ${GITPOD_REPO_ROOT}/start_all.sh
        chmod 777 ${GITPOD_REPO_ROOT}/stop_and_destroy_all.sh
      )
    command: |
      cd ${GITPOD_REPO_ROOT}
      ./start_all.sh region
      gp open 01_Lab_Setup.ipynb
ports:
  - port: 5433
    description: YSQL API Port
    onOpen: ignore
  - port: 7000
    description: YB-Master UI Port
    onOpen: notify
  - port: 7100
    description: YB-Master API Port
    onOpen: ignore
  - port: 8200
    description: YB-TServer UI Port
    onOpen: notify
  - port: 9000-9040
    description: Jupyter Notebook ports
    onOpen: ignore
  - port: 9042
    description: YCQL API Port
    onOpen: ignore
  - port: 9100
    description:  YB-TServer API Port
    onOpen: ignore
  - port: 12000
    description:  YB-TServer API Port
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 15433
    onOpen: open-browser
  - port: 37843
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow